apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: crm
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: Y3JtX3VzZXI=        # crm_user
  SPRING_DATASOURCE_PASSWORD: Y3JtX3Bhc3N3b3Jk    # crm_password