apiVersion: v1
kind: Service
metadata:
  name: crm-app
  namespace: crm
  labels:
    app: crm-app
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: crm-app
  ports:
    - name: http
      port: 8080
      targetPort: 8081
  sessionAffinity: ClientIP