apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crm-demo
  template:
    metadata:
      labels:
        app: crm-demo
    spec:
      containers:
        - name: crm-demo
          image: crm-demo:0.1
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
