apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: crm
type: Opaque
data:
  MARIADB_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk    # rootpassword
  MARIADB_DATABASE: Y3JtX2Ri                # crm_db
  MARIADB_USER: Y3JtX3VzZXI=                # crm_user
  MARIADB_PASSWORD: Y3JtX3Bhc3N3b3Jk        # crm_password