apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: crm
type: Opaque
data:
  MARIADB_ROOT_PASSWORD: cm9vdA==
  MARIADB_DATABASE: Y3Jt
  MARIADB_USER: Y3Jt
  MARIADB_PASSWORD: Y3JtMTIz
