apiVersion: v1
kind: Service
metadata:
  name: crm-frontend
  namespace: crm
  labels:
    app: crm-frontend
    tier: frontend
spec:
  type: NodePort
  selector:
    app: crm-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
  sessionAffinity: ClientIP