apiVersion: v1
kind: Service
metadata:
  name: crm-frontend
  namespace: crm
  labels:
    app: crm-frontend
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: crm-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  sessionAffinity: None